version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "simbo1905"
    assignees:
      - "simbo1905"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "chore(deps)"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "simbo1905"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci(actions)"