name: CI

on:
  push:
    branches: [ fix/ci ]

jobs:
  build:
    name: Build with Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [24]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'oracle'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache mvnd
      uses: actions/cache@v4
      with:
        path: ~/.m2/mvnd
        key: ${{ runner.os }}-mvnd-${{ matrix.java }}
        restore-keys: |
          ${{ runner.os }}-mvnd-

    - name: Install mvnd (Unix-like)
      if: runner.os != 'Windows'
      run: |
        if ! command -v mvnd &> /dev/null; then
          echo "Installing mvnd..."
          curl -fsSL https://github.com/apache/maven-mvnd/releases/download/1.0.2/maven-mvnd-1.0.2-${{ runner.os == 'macOS' && 'darwin-amd64' || 'linux-amd64' }}.tar.gz | tar xz -C ~/.m2
          echo "$HOME/.m2/maven-mvnd-1.0.2-${{ runner.os == 'macOS' && 'darwin-amd64' || 'linux-amd64' }}/bin" >> $GITHUB_PATH
        fi
